name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions

      - name: Type & Doc check
        run: deno check --doc

      - name: Check fmt
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run doc tests
        run: deno task test:docs

      - name: Run tests & generate coverage
        run: deno task test:ci

      - name: Generate coverage report
        run: deno task build:cov

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./cov.lcov
